apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: temp-priv-account
  namespace: {{ $.Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: temp-role-binding
  namespace: {{ $.Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: temp-priv-account
  namespace: {{ $.Values.namespace }}
