apiVersion: v1
kind: Service
metadata:
  labels:
    app: argotesting
  name: argo-test-service
  namespace: {{ $.Values.namespace }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: argotesting
